name: Checkmarx SAST Scan
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@<version>
      with:
        cxServer: http://113.53.184.16:9080
        cxUsername: admin
        cxPassword: ${{ secrets.CX_PASSWORD }}
        cxTeam: \CxServer
